Nextjs paths
widgetbot-io/embed pull request #257
Opened 2023-04-23 17:44 UTC by tylergeorges

Added semantic path linking in TSConfig Paths

2023-04-24 14:37 UTC, Yomanz requested changes

2023-04-24 14:37 UTC, Yomanz commented on src/components/Core/index.tsx
> +import { styled, css, theme } from '@stitches-config';
Is there any reason this cant just be @stitches?

2023-04-24 17:06 UTC, mason-rogers requested changes
looks good other than that single thing, and agree with @Yomanz that @stitches-config should probably just be called @stitches for cleanliness

2023-04-24 17:06 UTC, mason-rogers commented on src/pages/channels/[guild]/index.tsx
> +import { getEnvVar } from '@util/env';
this can be changed to `from '@util'`

2023-04-24 17:36 UTC, tylergeorges commented on src/pages/channels/[guild]/index.tsx
> +import { getEnvVar } from '@util/env';
alright changing them now

2023-04-26 13:05 UTC, Yomanz approved these changes
LGTM

2023-04-26 13:05 UTC, merged