Feature/nextjs messages
widgetbot-io/embed pull request #273
Opened 2023-06-06 21:03 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

I accidentally started making new feature branches off of other feature branches instead of working off of the root branch, so this branch is a combination of  nextjs-threads, nextjs-loading-screen, nextjs-tooltip, nextjs-modal. 

Features:
 - Added react virtualized list for rendering messages 
 _ Adding loading screen 
 - Added tooltip HOC 
 - Added animated modal HOC
 - Added a threads panel/popout to open threads for the current channel
 
 Fixed:
  - Converted hardcoded styled values and to styled tokens for a more consistent design 
  - Removed the old custom stitches styled function and replaced it with a working version
  - Converted media queries and inline css to variants in the styled component declaration

2023-06-29 11:55 UTC, Yomanz requested changes
You need to localise all the english strings in the code.

2023-06-29 12:37 UTC, mason-rogers requested changes

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/IconButton.tsx
> +  onClick: (arg0: any) => void;
Should this have a proper type? I see you used React.SyntheticEvent for onClicks in previous code (also the arg name, `arg0` should have a proper name)

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/elements.ts
> +    'url(https://emerald.widgetbot.io/static/media/15e026451fd814e2d1a13e49c8076978.15e02645.png)',
Should be a local asset

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/elements.ts
> +  backgroundPositionX: 'var(--emoji-x)',
What supplies this? and var(--emoji-y)

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/elements.ts
> +    path: {
instead of styling the path itself, the svg can use `color="currentColor"` and then we can use `color` prop to set it, and the svg will inherit the color

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/index.tsx
> +          css={
This formatting looks super hard to read, I would say make a variable above the return called `iconStyles` or something, and define it there - then just do `css={iconStyles}`

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/index.tsx
> +          css={
Same here

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/index.tsx
> +  return (
We can split the content inside the <Tooltip> into its own component, this means we dont have to repeat the code for if the tooltip is enabled or not. And it is just defined once above.

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/PinButton/index.tsx
> +      onClick={handlePinClick}
```suggestion
      onClick={(e) => e.preventDefault()}
```

 and remove handlePinClick function above

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/ThreadsButton/index.tsx
> +  const openThreadsModal = useCallback(
Does this need to be in a useCallback, what happens if it isn't? This should work with just openThreadsModel being a method

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/ThreadsPanelButton/index.tsx
> +      iconBackgroundSize={40}
Might be better with a variant, worth playing around with

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Icons.tsx
> +export interface IconProps {
Would this interface be cleaner if extending the props of IconRoot?

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Icons.tsx
> +export interface IconProps {
`export interface IconProps extends React.ComponentProps<typeof IconRoot>`

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/NoThreadsIcon/index.tsx
> +      <Icons name="ThreadHash" size="large" css={{ textAlign: 'center' }} />
Variant for center ideally

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/Spine/index.tsx
> +  <SpineIconRoot width="12" height="11" viewBox="0 0 12 11" fill="none" aria-hidden="true">
Might be cleaner as a file, play around with it

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/Icons/ThreadsPanelIcon/index.tsx
> +  <ThreadsPanelIconRoot
Same as above

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/ToolTip/elements.ts
> +  backgroundColor: '#18191c',
Hardcoded color, should be added as part of the stitches config

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/ToolTip/index.tsx
> +  const openToolTip = () => {
Should just be a single setTooltip(true/false) method rather than an open & close

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Shared/ToolTip/index.tsx
> +        css={
Define the styles above the return and it will likely look a lot cleaner & more readable

2023-06-29 12:37 UTC, mason-rogers commented on src/components/Sidebar/ChannelsList/Category/ChannelsContainer/Channel.tsx
> +    const currentGuildUrl = useMemo(() => `/channels/${guildID}`, [guildID]);
Doesn't need a useMemo

2023-06-29 20:50 UTC, Yomanz commented on src/components/Core/TextChannelContainer/MessageSkeleton.tsx
> +const FirstSkeletonLine = () => (
@mason-rogers the skeletons should be the same each render, but each line should be different.

2023-07-12 02:49 UTC, tylergeorges commented
> You need to localise all the english strings in the code.

Should be done in the newest commit

2023-07-13 01:50 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/MessageContainer.tsx
> +    channel: '585840022511550494',
resolved

2023-07-13 01:51 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/MessageContainer.tsx
> +      className="message-wrapper "
updated all styled components with the new withConfig function and removed all unnecessary classnames from said components

2023-07-13 02:10 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/elements.ts
> +export const TextChannelWrapper = styled('div', 'text-channel_wrapper', {
fixed and resolved in newest push :)

2023-07-13 02:11 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/MessageSkeleton.tsx
> +const FirstSkeletonLine = () => (
Not going to worry about this for now as It's not implemented anywhere in the embed yet

2023-07-13 02:12 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/MessageContainer.tsx
> +import { MessageWrapper } from './elements';
Resolved

2023-07-13 02:12 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/elements.ts
> +});
Resolved

2023-07-13 02:13 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/elements.ts
> +  variants: {
This should be resolved now? I might've missed a spot

2023-07-13 02:21 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/elements.ts
> +    fontSize: `${theme.space['2xl']}`,
Yeah this was unnecessary in the first place, should be resolved now

2023-07-13 02:21 UTC, tylergeorges commented on stitches.config.tsx
> +      '2xl': '32px'
Resolved

2023-07-13 02:21 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/elements.ts
> +  marginBottom: '$lg',
REsolved

2023-07-13 02:23 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/elements.ts
> +  marginTop: 5,
Yeah, I really only used hardcoded values because it didn't make sense to keep adding tokens just for them to ever be used once, especially for the skeleton loader

2023-07-13 02:24 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/index.tsx
> +      // @ts-ignore
Resolved, I just removed it as its not needed

2023-07-13 02:24 UTC, tylergeorges commented on src/components/Core/VirtualLists/MessageRenderer.tsx
> +    <div style={{ position: 'relative', width: '100%', height: '100%', boxSizing: 'content-box' }}>
Resolved

2023-07-13 02:24 UTC, tylergeorges commented on src/components/Core/VirtualLists/MessageRenderer.tsx
> +          style={{
Resolved, I just removed the styles and it still works fine.

2023-07-13 02:25 UTC, tylergeorges commented on src/components/Core/VirtualLists/staticData.ts
> +import { APIMessage, APIUser, MessageType } from 'discord-api-types/v10';
Resolved

2023-07-13 02:29 UTC, tylergeorges commented on src/components/Core/index.tsx
> +  from: { transform: 'scale(0.90)', opacity: 0 },
Resolved

2023-07-13 02:30 UTC, tylergeorges commented on src/components/Core/index.tsx
> +    backgroundColor: `${theme.colors.primaryOpacity10} !important`,
Resolved, I removed all !importants

2023-07-13 02:32 UTC, tylergeorges commented on src/components/Core/index.tsx
> +    backgroundColor: 'rgb(0, 0, 0, 0.5)',
Are you referring to the backgroundColor?

2023-07-13 02:33 UTC, tylergeorges commented on src/components/Header/ChannelHeader/index.tsx
> +          <ChannelHeaderName className="text-channel_header_name">{currentChannel?.name}</ChannelHeaderName>
Resolved, I added a skeleton loader for if the channel information isnt set

2023-07-13 02:35 UTC, tylergeorges commented on src/components/Header/ThreadPanelHeader/index.tsx
> +            <Icons name="ThreadHash" color="dark" css={{ marginX: '$sm' }} />
Icons is a reusable icon component i made that has all of discord svgs

2023-07-13 02:36 UTC, tylergeorges commented on src/components/Header/ThreadPanelHeader/index.tsx
> +            {currentThread?.name}
Resolved

2023-07-13 02:38 UTC, tylergeorges commented on src/components/Header/elements.tsx
> +export const ThreadPanelHeaderContainer = styled(
Its not empty, it inherits all of the styles from the ChannelHeaderContainer

2023-07-13 02:40 UTC, tylergeorges commented on src/components/Header/elements.tsx
> +export const HeaderRoot = styled(Root, 'header-root', {});
Resolved, Its not empty, it inherits all of the styles from the Root element, but I just removed the whole file because it wasn't needed anyway

2023-07-13 02:41 UTC, tylergeorges commented on src/components/Header/elements.tsx
> +export const GuildHeaderName = styled(HeaderMainContentRoot, 'guild-header_name', {});
Its inheriting the styles

2023-07-13 02:42 UTC, tylergeorges commented on src/components/Header/elements.tsx
> +        display: 'flex',
Resolved

2023-07-13 02:43 UTC, tylergeorges commented on stitches.config.tsx
>      singleChannel: {
I never added these, these were there from when i first started working on the embed, I left everything that was there before I started working on it just in case it would be needed

2023-07-13 02:45 UTC, tylergeorges commented on src/components/Header/elements.tsx
> +  '@media (max-width: 270px), (max-height: 300px)': {
Resolved

2023-07-13 02:45 UTC, tylergeorges commented on src/components/Header/elements.tsx
> +  '.text-channel_header_buttons_container': {
Resolved, this file got deleted

2023-07-13 02:46 UTC, tylergeorges commented on src/components/Header/elements.tsx
> +    fontFamily: 'var(--font-display)',
Resolved, I deleted the file

2023-07-13 02:46 UTC, tylergeorges commented on src/components/Header/elements.tsx
> +const name = (hash: typeof Hash) =>
Resolved, I deleted the file

2023-07-13 02:50 UTC, tylergeorges commented on src/components/Header/index.tsx
> +      children || (
Resolved

2023-07-13 02:51 UTC, tylergeorges commented on src/components/Overlays/ContextMenu/index.tsx
> +      .then(() => {})
Resolved

2023-07-13 02:55 UTC, tylergeorges commented on src/components/Overlays/Loading/elements.ts
> +      fetchingMessages: {
Resolved

2023-07-13 02:55 UTC, tylergeorges commented on src/components/Overlays/Loading/elements.ts
> +      fetchingMessages: {
Resolved

2023-07-13 02:57 UTC, tylergeorges commented on src/components/Overlays/Modal/Popout/ThreadsPopout.tsx
> +  const childrenRef = useRef<HTMLDivElement>(null);
If left empty it throws a type error

2023-07-13 03:01 UTC, tylergeorges commented on src/components/Overlays/Modal/Popout/ThreadsPopout.tsx
> +  const channelHasThreads = useMemo(
Resolved

2023-07-13 03:03 UTC, tylergeorges commented on src/components/Overlays/Modal/Popout/index.tsx
> +  if (popoutFor && isOpen) {
Resolved

2023-07-13 03:07 UTC, tylergeorges commented on src/components/Overlays/Modal/elements.ts
> +const zoomIn = keyframes({
They both are different animations, the one used for modals is more of bouncy zoom in while the zoomIn used on startup just zooms in,  I went ahead and changed the name of the modal zoomIn to zoomInBounce so this should be resolved

2023-07-13 03:08 UTC, tylergeorges commented on src/components/Overlays/Modal/elements.ts
> +export const PopoutContainerWrapper = styled(ModalContainerWrapper, 'popout-container_wrapper', {});
It inherits all of the styles from ModalContainerWrapper

2023-07-13 03:09 UTC, tylergeorges commented on src/components/Overlays/Modal/elements.ts
> +  cursor: 'default'
Resolved, the file is deleted

2023-07-13 03:14 UTC, tylergeorges commented on src/components/Overlays/Modal/elements.ts
> +export const PopoutWrapper = styled(ModalContainerWrapper, 'popout-wrapper', {});
Resolved, file got deleted.

2023-07-13 03:14 UTC, tylergeorges commented on src/components/Overlays/Modal/elements.ts
> +      true: {},
Resolved, file deleted.

2023-07-13 03:16 UTC, tylergeorges commented on src/components/Overlays/Modal/index.tsx
> +  children: ReactElement<any, any>[];
Really? It doesnt throw any type errors but I'll change it to ReactNode

2023-07-13 03:19 UTC, tylergeorges commented on src/components/Overlays/Modal/index.tsx
> +    {!disableBackdrop && <ModalBackdrop isOpen={isOpen} onClick={hideModal} css={{ zIndex: 12 }} />}
Resolved, added zIndex tokens and depending what its a backdrop for it will have the approriate zIndex for example, backdrops for modals should always be on top of everything except the modal itself, so the modal backdrop gets a zIndex of 60

2023-07-13 03:19 UTC, tylergeorges commented on src/components/Providers/GuildProvider.tsx
> +      // router.push('/channels/585454996800405509/585840022511550494');
Resolved

2023-07-13 03:20 UTC, tylergeorges commented on src/components/Shared/Channel/elements.ts
> +  backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='20' height='20' viewBox='0 0 24 24' class='icon-1_QxNX'%3E%3Cpath fill='rgba(255,255,255,0.3)' fill-rule='
Resolved, moved all icons to an Icons component

2023-07-13 03:22 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/EmojisButton/index.tsx
> +    <IconButtonWrapper tooltipDisabled onClick={addEmoji}>
Resolved

2023-07-13 03:25 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/Hamburger/elements.tsx
> +  '&:hover': {
For some reason this breaks it

2023-07-13 03:26 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButton.tsx
> +  onClick: (arg0: any) => void;
Resolved

2023-07-13 04:32 UTC, tylergeorges commented on src/components/Overlays/Modal/elements.ts
> +export const PopoutContainerWrapper = styled(ModalContainerWrapper, 'popout-container_wrapper', {});
Resolved, Deleted file

2023-07-13 04:32 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/elements.ts
> +    'url(https://emerald.widgetbot.io/static/media/15e026451fd814e2d1a13e49c8076978.15e02645.png)',
Resolved

2023-07-13 04:33 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/elements.ts
> +  backgroundPositionX: 'var(--emoji-x)',
It gets supplied from the EmojiIcon button as a css variable, its used to choose a new emoji to display from the emoji grid in the image

2023-07-13 04:40 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/elements.ts
> +    path: {
Oh cool didnt know this

2023-07-13 04:49 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/elements.ts
> +    path: {
Resolved

2023-07-13 04:57 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/index.tsx
> +          css={
resolved

2023-07-13 04:57 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/index.tsx
> +          css={
resolved

2023-07-13 05:00 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/PinButton/index.tsx
> +      onClick={handlePinClick}
Resolved

2023-07-13 05:01 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/ThreadsButton/index.tsx
> +  const openThreadsModal = useCallback(
Resolved

2023-07-13 05:02 UTC, tylergeorges commented on src/components/Shared/Icons/EmojisIcon/index.tsx
> +    const emojisInLastRow = 5;
Oh yeah I just had those so I didnt get confused, I Removed them though

2023-07-13 05:03 UTC, tylergeorges commented on src/components/Shared/Icons/EmojisIcon/index.tsx
> +    const emojisInLastRow = 5;
Resolved

2023-07-13 05:06 UTC, tylergeorges commented on src/components/Shared/Icons/Icons.tsx
> +export interface IconProps {
Resolved, didn't think of this thanks!

2023-07-13 05:08 UTC, tylergeorges commented on src/components/Shared/Icons/Spine/index.tsx
> +  <SpineIconRoot width="12" height="11" viewBox="0 0 12 11" fill="none" aria-hidden="true">
Resolved, its the component "ThreadsSpine" now

2023-07-13 05:09 UTC, tylergeorges commented on src/components/Shared/Icons/NoThreadsIcon/index.tsx
> +      <Icons name="ThreadHash" size="large" css={{ textAlign: 'center' }} />
Resolved, removed the css from the ThreadHash icon

2023-07-13 11:54 UTC, Yomanz commented on src/components/Core/index.tsx
> +    backgroundColor: 'rgb(0, 0, 0, 0.5)',
Yes

2023-07-13 11:55 UTC, Yomanz commented on src/components/Overlays/Modal/Popout/ThreadsPopout.tsx
> +  const childrenRef = useRef<HTMLDivElement>(null);
`const childrenRef = useRef<T>();` should give the type of `T | undefined`.

2023-07-13 12:21 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/index.tsx
> +  return (
So make two different icon buttons one that has tooltips and another one without? A little confused by what you mean

2023-07-13 12:22 UTC, Yomanz commented on src/components/Shared/Icons/Buttons/Hamburger/elements.tsx
> +  '&:hover': {
```suggestion
  '&:hover, &::before': {
```

@mason-rogers made a typo

2023-07-13 12:22 UTC, Yomanz commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/elements.ts
> +  backgroundPositionX: 'var(--emoji-x)',
Just leave a comment explaining where it comes from in the code and that's fine so it's clear.

2023-07-13 12:26 UTC, tylergeorges commented on src/components/Core/index.tsx
> +    backgroundColor: 'rgb(0, 0, 0, 0.5)',
Resolved, I just removed the component entirely as it's not even being used anywhere

2023-07-13 16:11 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/ThreadsPanelButton/index.tsx
> +      iconBackgroundSize={40}
Resolved, I made the backgroundGlowSize variant

2023-07-13 17:13 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/index.tsx
> +  return (
Resolved

2023-07-14 13:44 UTC, Yomanz commented on next.config.js
> +  reactStrictMode: false,
Why?

2023-07-14 13:44 UTC, Yomanz commented on src/components/Shared/Icons/Buttons/ThreadsButton/index.tsx
> +      tooltipLabel="Threads"
Needs localising.

2023-07-14 16:36 UTC, tylergeorges commented on next.config.js
> +  reactStrictMode: false,
I thought this was causing use messages to render twice, its added back now as the re renders are caused by something else

2023-07-14 16:36 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/ThreadsButton/index.tsx
> +      tooltipLabel="Threads"
Resolved

2023-07-16 12:58 UTC, JohnyTheCarrot requested changes
Will continue review later, disregard for now. We'll let you know once you can start applying changes.

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Core/TextChannelContainer/TextBox/index.tsx
> +    if (fileAttachmentElement) {
Nitpick, but:
```suggestion
    fileAttachmentElement?.click();
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Core/TextChannelContainer/index.tsx
> +    // Used to hide mmbers list if the threads panel is open
```suggestion
    // Used to hide members list if the threads panel is open
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Core/TextChannelContainer/styles.ts
> +        width: `calc(100% - ${theme.sizes.threadPanelMinWidth} + 8px)`
Should this `8px` not be tokenized?

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Core/TextChannelContainer/styles.ts
> +  // position: 'relative',
```suggestion
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Core/TextChannelContainer/styles.ts
> +  // position: 'relative',
```suggestion
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Core/TextChannelContainer/styles.ts
> +  cursorColor: 'white',
Why is this here?

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Header/ChannelHeader/index.tsx
> +          {currentChannel ? (
Use one ternary

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Header/index.tsx
> +    {children && children}
```suggestion
    {children}
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Overlays/Modal/InformationModal/ChannelTopicModal.tsx
> +      title={(currentChannel && currentChannel.name) || ''}
```suggestion
      title={currentChannel?.name ?? ''}
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Overlays/Modal/InformationModal/index.tsx
> +      <Styles.ModalHeaderContent className="non-dragable">
Remove the `non-dragable` class, because:
1. You shouldn't be using raw classes.
2. Your class defines the browser variants which is redundant bc the CSS-in-JS libraries do this for you.
3. Just add `user-select: none` to the styled components.

```suggestion
      <Styles.ModalHeaderContent>
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Overlays/Modal/Popout/ThreadsPopout/ChannelThreads.tsx
> +          <Fragment key={thread.id}>
```suggestion
          <ThreadPopoutItem thread={thread} key={thread.id} />
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Overlays/Modal/Popout/index.tsx
> +type TitleIcon = Pick<IconProps, 'icon'>['icon'];
```suggestion
type TitleIcon = IconProps['icon'];
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Shared/Icons/Buttons/EmojisButton/index.tsx
> +  <IconButtonWrapper tooltipDisabled onClick={e => e.preventDefault()}>
Are you sure you're running prettier? Prettier usually applies parenthesis around the parameters of a lambda function.

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/IconButtonInner.tsx
> +    {iconContent && <IconContent content={iconContent} />}
```suggestion
    {iconContent && (
        <Styles.IconButtonContentWrapper>{iconContent}</Styles.IconButtonContentWrapper>
     )}
```

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Shared/Icons/NoThreadsIcon/index.tsx
> +        css={{ position: 'absolute', width: 104, height: 80, left: -1 }}
Use a styled component

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Shared/Icons/index.tsx
> +  <>
Redundant fragment

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Sidebar/ChannelsSidebar/Category/ChannelsContainer/Channel.tsx
> +              {channel.type === ChannelType.GuildText && (
Use function component with switch

2023-07-16 12:58 UTC, JohnyTheCarrot commented on src/components/Sidebar/ChannelsSidebar/Category/ChannelsContainer/index.tsx
> +                        channelHasActiveThread={!!threadId && channel.id === channelId}
```suggestion
                        channelHasActiveThread={threadId && channel.id === channelId}
```

or if it really needs to be a boolean
```suggestion
                        channelHasActiveThread={Boolean(threadId) && channel.id === channelId}
```

2023-07-17 17:34 UTC, JohnyTheCarrot requested changes
review done

2023-07-19 13:40 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/TextBox/index.tsx
> +    if (fileAttachmentElement) {
Resolved

2023-07-19 13:40 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/index.tsx
> +    // Used to hide mmbers list if the threads panel is open
Resolved

2023-07-19 13:41 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/styles.ts
> +  // position: 'relative',
Resolved

2023-07-19 13:41 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/styles.ts
> +  // position: 'relative',
Resolved

2023-07-19 13:43 UTC, tylergeorges commented on src/components/Header/ChannelHeader/index.tsx
> +          {currentChannel ? (
Resolved

2023-07-19 13:43 UTC, tylergeorges commented on src/components/Header/index.tsx
> +    {children && children}
Resolved

2023-07-19 13:44 UTC, tylergeorges commented on src/components/Overlays/Modal/InformationModal/ChannelTopicModal.tsx
> +      title={(currentChannel && currentChannel.name) || ''}
Resolved

2023-07-19 13:51 UTC, tylergeorges commented on src/components/Overlays/Modal/InformationModal/index.tsx
> +      <Styles.ModalHeaderContent className="non-dragable">
Resolved

2023-07-19 13:53 UTC, tylergeorges commented on src/components/Overlays/Modal/Popout/ThreadsPopout/ChannelThreads.tsx
> +          <Fragment key={thread.id}>
Resolved

2023-07-19 13:57 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/EmojisButton/index.tsx
> +  <IconButtonWrapper tooltipDisabled onClick={e => e.preventDefault()}>
Yes I have prettier, maybe the custom config we have doesn't do this?

2023-07-19 13:58 UTC, tylergeorges commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/IconButtonInner.tsx
> +    {iconContent && <IconContent content={iconContent} />}
Resolved

2023-07-19 14:03 UTC, tylergeorges commented on src/components/Shared/Icons/NoThreadsIcon/index.tsx
> +        css={{ position: 'absolute', width: 104, height: 80, left: -1 }}
Resolved

2023-07-19 14:04 UTC, tylergeorges commented on src/components/Shared/Icons/index.tsx
> +  <>
Resolved

2023-07-19 14:16 UTC, tylergeorges commented on src/components/Sidebar/ChannelsSidebar/Category/ChannelsContainer/index.tsx
> +                        channelHasActiveThread={!!threadId && channel.id === channelId}
Throws type error without double bang

2023-07-19 15:16 UTC, tylergeorges commented on src/components/Sidebar/styles.ts
> +        '@mobile': {
Resolved

2023-07-19 15:17 UTC, tylergeorges commented on src/hooks/useMessages.ts
> +    // @ts-ignore
Resolved

2023-07-19 15:22 UTC, tylergeorges commented on src/components/Sidebar/ChannelsSidebar/styles.ts
> +  displayName: 'channel-name'
channel-name is manually defined so the channel highlighter component and channel name elements styles are consistent with eachother

2023-07-20 15:46 UTC, Yomanz requested changes
Some final finishing touches

2023-07-20 15:46 UTC, Yomanz commented on src/components/Core/TextChannelContainer/MessageContainer.tsx
> +    thread: ''
Shouldn't be an empty string, should be undefined.

2023-07-20 15:46 UTC, Yomanz commented on src/components/Core/TextChannelContainer/TextBox/TextBoxInput.tsx
> +    if (
Change this to ![].includes

2023-07-20 15:46 UTC, Yomanz commented on src/hooks/useMessages.ts
> +const EmbedFragment = gql`
Lets get this GraphQL stuff in its own file.

2023-07-20 15:54 UTC, JohnyTheCarrot approved these changes

2023-07-20 16:04 UTC, mason-rogers approved these changes

2023-07-20 16:37 UTC, Yomanz approved these changes
LGTM

2023-07-20 16:37 UTC, merged