Feature/nextjs sub
widgetbot-io/embed pull request #281
Opened 2023-07-24 15:38 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

Branch that adds websocket subscriptions to current discord channel such as new messages, updated messages, and deleted messages

2023-07-26 18:11 UTC, Yomanz requested changes
a few changes needed, otherwise great work!

You need to improve the subscriptions code, there is a lot of duplication and you should not be using any deprecated subscriptions.

2023-07-26 18:11 UTC, Yomanz commented on src/components/Core/TextChannelContainer/ThreadChannelContainer/index.tsx
> +
👺

2023-07-26 18:11 UTC, Yomanz commented on src/components/Overlays/Modal/Popout/ThreadsPopout/ChannelThreads.tsx
> +  const setIsCurrentChannelThread = useStoreActions(state => state.ui.setIsCurrentChannelThread);
This could be computed rather than stored.

2023-07-26 18:11 UTC, Yomanz commented on src/graphql/client.ts
> +  url: `https://${getEnvVar('CUSTOM_SERVER_ENDPOINT')}/api/graphql`,
Can you add a http/https check, similar to the ws/wss one

2023-07-26 18:11 UTC, Yomanz commented on src/hooks/messagesQuery/index.ts
> +    messageUpdate(channel: $channel, guild: $guild) {
What if anything apart from the content is updated?

2023-07-26 18:11 UTC, Yomanz commented on src/hooks/messagesQuery/index.ts
> +    messageUpdate(channel: $channel, guild: $guild) {
Also, this should be using `messageUpdateV2`

2023-07-26 18:11 UTC, Yomanz commented on src/hooks/messagesQuery/index.ts
> +    message(guild: $guild, channel: $channel) {
Use `messageV2`

2023-07-26 18:11 UTC, Yomanz commented on src/hooks/messagesQuery/index.ts
> +    messageDelete(channel: $channel, guild: $guild) {
Use `messageDeleteV2`

2023-07-26 18:11 UTC, Yomanz commented on src/hooks/useClient.ts
What is this?

2023-07-26 18:11 UTC, Yomanz commented on src/hooks/useSub.ts
> +export const useSub = ({ messages, setMessages, channel, guild }: UseSubArgs) => {
Rename this to something better such as `useMessageSubscription` or something regarding live updates.

2023-07-26 18:11 UTC, Yomanz commented on src/util/convertMessageToDiscord.ts
> +  edited_timestamp: message.editedAt,
Shouldn't this be parsed similarly to timestamp.

2023-07-26 21:19 UTC, tylergeorges commented on src/hooks/useClient.ts
Its a hook to get the urql client, I ended up not needing it though

2023-07-27 12:49 UTC, tylergeorges commented on src/util/convertMessageToDiscord.ts
> +  edited_timestamp: message.editedAt,
Parsing it like timestamp breaks it and marks all messages as edited

2023-07-27 12:50 UTC, tylergeorges commented on src/components/Overlays/Modal/Popout/ThreadsPopout/ChannelThreads.tsx
> +  const setIsCurrentChannelThread = useStoreActions(state => state.ui.setIsCurrentChannelThread);
You mean by checking if the query param is in URL?

2023-07-27 13:27 UTC, Yomanz commented on src/util/convertMessageToDiscord.ts
> +  edited_timestamp: message.editedAt,
Did you add a falsey check?

Does it work like this?

2023-07-27 13:52 UTC, tylergeorges commented on src/util/convertMessageToDiscord.ts
> +  edited_timestamp: message.editedAt,
Yes it works as it is now

2023-07-27 13:54 UTC, Yomanz commented on src/util/convertMessageToDiscord.ts
> +  edited_timestamp: message.editedAt,
Alright

2023-07-27 14:55 UTC, Yomanz commented on src/hooks/messagesQuery/index.ts
>        id
Use a fragment

2023-07-27 14:55 UTC, Yomanz commented on src/hooks/messagesQuery/index.ts
> +  subscription ThreadMessageDeleted($channel: String!, $guild: String!, $threadId: String) {
Why are all the subs duplicated?

2023-07-27 14:56 UTC, Yomanz commented on src/hooks/useThreadSubscription.ts
> +export const useThreadSubscription = ({
Why is this separate from useMessageSubscription?

2023-07-27 16:59 UTC, Yomanz requested changes

2023-07-27 16:59 UTC, Yomanz commented on src/hooks/useMessageSubscription.ts
> +  setMessages: Dispatch<SetStateAction<Array<StateMessages>>>;
```suggestion
  setMessages: Dispatch<SetStateAction<StateMessages[]>>;
```

2023-07-27 18:49 UTC, Yomanz approved these changes

2023-07-28 00:42 UTC, mason-rogers commented on src/components/Core/index.tsx
> +export const Main = styled('main', 'main', {
shouldnt this be using the commonComponentId/displayName stuff for re-usable class names

2023-07-28 00:42 UTC, mason-rogers commented on src/components/Core/index.tsx
> +export const InnerMain = styled('div', 'inner-main', {
Same as above

2023-07-28 12:58 UTC, JohnyTheCarrot commented on src/components/Core/index.tsx
> +export const Main = styled('main', 'main', {
it should indeed, mason

2023-07-28 13:08 UTC, Yomanz approved these changes
![Woah](https://media.tenor.com/oZH0oT4vZcoAAAAC/karl-pilkington.gif)

2023-07-28 13:30 UTC, mason-rogers approved these changes

2023-07-28 13:36 UTC, merged