Feature/nextjs auth
widgetbot-io/embed pull request #286
Opened 2023-08-01 20:02 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

This Pull Request allows the user to log in/log out using their Discord account.

How it works:
- User clicks Login button which opens a new window that redirects to Discord's auth login
- This returns the user's token which is then stored in local storage and used to request information about the user
- On app startup, along with requesting guild info in GuildProvider, it also gets the user's token from local storage and requests info about the user and then stores it in the User store
- When the user logouts, we remove their token from local storage and clear the User store

2023-08-13 12:20 UTC, Yomanz requested changes

2023-08-13 12:20 UTC, Yomanz commented on src/components/Overlays/Modal/styles.ts
> +  // @ts-ignore
Don't use @ts-ignore, use @ts-expect-error if you must.

2023-08-13 12:20 UTC, Yomanz commented on src/components/Overlays/Modal/styles.ts
> +  // zIndex: theme.zIndices.modal,
```suggestion

```

2023-08-13 12:20 UTC, Yomanz commented on src/components/Sidebar/ChannelsSidebar/Category/index.tsx
> +      console.log('shouldnt refecth ', currentChannelRef.current.offsetTop);
```suggestion
```

2023-08-13 12:20 UTC, Yomanz commented on src/components/Sidebar/ChannelsSidebar/Category/index.tsx
> +      console.log('should refecth ', currentChannelRef.current.offsetTop);
```suggestion
```

2023-08-13 12:20 UTC, Yomanz commented on src/components/Sidebar/ChannelsSidebar/ChannelsFooter/ChannelsFooterUserInfo.tsx
> +        alt={`@${user.username}'s Avatar.`}
Localise

2023-08-13 12:20 UTC, Yomanz commented on src/state/stores/ui.ts
> +      console.log(state.currentChannelYPos, payload);
```suggestion
```

2023-08-13 12:20 UTC, Yomanz commented on src/state/stores/user.ts
> +  data?: DiscordUser | GuestUser | GuildUser;
Use the `AuthUser` type here.

2023-08-13 12:20 UTC, Yomanz commented on src/types/user.types.ts
> +  _id: string;
This should be `id`, not `_id`.

2023-08-13 12:20 UTC, Yomanz commented on src/types/user.types.ts
> +  blockedUsers: DiscordUser[];
This is an array of IDs, not users.

2023-08-13 12:31 UTC, Yomanz commented on src/pages/channels/[guild]/[channel].tsx
> +      // @ts-ignore
See other ts-ignore comment.

2023-08-13 12:34 UTC, mason-rogers requested changes

2023-08-13 12:34 UTC, mason-rogers commented on src/hooks/useAuthAPI.ts
> +export const useAuthAPI = () => {
Can we use Api instead of API, this includes typings such as APIDiscordResponse -> ApiDiscordResponse

2023-08-13 12:34 UTC, mason-rogers commented on src/components/Overlays/Modal/GuestFormModal/index.tsx
> +  const discordLoginCB = () => {
This function is useless, just call discordSignIn() directly

2023-08-13 12:34 UTC, mason-rogers commented on src/components/Overlays/Modal/GuestFormModal/index.tsx
> +  const hasUser = !!user;
seems a bit pointless, i would just use !!user where needed

2023-08-13 12:34 UTC, mason-rogers commented on src/components/Providers/DataProvider.tsx
> +  const isFetching = !isUserFetched || !isGuildFetched;
imo this should be inversed, call it isFetched and do `isUserFetched && isGuildFetched` - would be more readable

2023-08-13 12:34 UTC, mason-rogers commented on src/lib/api/apiRequest.ts
> +export const fetchDiscordUser = ({ userToken }: { userToken?: string }) =>
2 Things

- The name is wrong, this doesn't exclusively fetch discord user - this returns info for guest tokens/anti-impersonation tokens too - it should be called fetchLatestProfile or fetchLatestUser.
- Please abstract the type `{ userToken?: string}` into an interface or something rather than inlining, it looks quite messy imo (this also goes for the reqs below it)

2023-08-13 12:34 UTC, mason-rogers commented on src/graphql/client.ts
> +    token = localStorage.getItem('token') ?? '';
```suggestion
    return localStorage.getItem('token') ?? '';
```

With this you can remove the const and the return below the trycatch

2023-08-13 12:40 UTC, mason-rogers commented on src/components/Overlays/Modal/styles.ts
> +  // @ts-ignore
*And comment why needed

2023-08-16 19:34 UTC, Yomanz approved these changes
Good stuff!

2023-08-16 19:34 UTC, Yomanz commented on src/types/user.types.ts
> +  _id: string;
^

2023-08-16 19:34 UTC, Yomanz commented on src/util/convertToDiscord/convertUserToDiscord.ts
> +    id: '_id' in user ? user._id : user.id,
You can change to `id` now.

2023-08-16 23:35 UTC, mason-rogers requested changes

2023-08-16 23:35 UTC, mason-rogers commented on src/components/Shared/Icons/Buttons/LogoutButton/index.tsx
> +  const translate = useTranslation();
This is a nitpick and im not sure if @Yomanz agrees, but imo we should use `const { t } = useTranslation()`, so example usage would be `tooltipLabel={t('logout.tooltip') as string` which imo is nicer.

If we decide to go through with this, this should be applied everywhere (search `useTranslation()`), not just here

2023-08-16 23:35 UTC, mason-rogers commented on src/components/Sidebar/ChannelsSidebar/ChannelsFooter/index.tsx
> +  useEffect(() => {
```suggestion
  useEffect(() => setShowGuestFormModal(!user), [setShowGuestFormModal, user])
```

2023-08-16 23:35 UTC, mason-rogers commented on src/components/Sidebar/ChannelsSidebar/ChannelsFooter/index.tsx
> +      {!user ? <ChannelsFooterLoginButton /> : <ChannelsFooterUserInfo />}
Imo this is more readable rather than inversing just to change the ternary order

```suggestion
      {user ? <ChannelsFooterUserInfo /> : <ChannelsFooterLoginButton />}
```

2023-08-16 23:35 UTC, mason-rogers commented on src/components/Sidebar/ChannelsSidebar/ChannelsFooter/index.tsx
> +      <Styles.ChannelsFooterVersionWrapper>WidgetBot v3.8.6</Styles.ChannelsFooterVersionWrapper>
Not sure if this is in another PR as discussed in discord or if you're adding it to this one.

But this should be from package.json (`WidgetBot ${package.version}`)

2023-08-17 13:23 UTC, Yomanz requested changes

2023-08-17 13:23 UTC, Yomanz commented on src/components/Shared/Icons/Buttons/LogoutButton/index.tsx
> +  const translate = useTranslation();
Yeah it needs to be destructured.

2023-08-17 13:28 UTC, Yomanz submitted a review, later dismissed

2023-08-18 00:22 UTC, advaith1 commented
this [doesnt build](https://vercel.com/widget-bot/embed/3BUxHQevc2jHHRm5T6igPmqxd4JR) and has a bunch of merge conflicts, those need to be fixed so this can be tested

2023-08-18 00:34 UTC, advaith1 requested changes
some code comments; will test it out and give more feedback once it builds

2023-08-18 00:34 UTC, advaith1 commented on src/components/Providers/UserProvider.tsx
> +      const token = localStorage.getItem('token');
before doing login/accessing localstorage there should always be a try/catch that shows an error popup if localstorage cant be accessed. accessing localstorage will error in an incognito iframe

![image](https://github.com/widgetbot-io/embed/assets/11778454/02f494d2-1e44-4553-9132-62f1fc034710)

2023-08-18 00:34 UTC, advaith1 commented on src/lib/api/apiRequest.ts
> +});
can we remove the axios dependency and move to native `fetch`

2023-08-18 00:34 UTC, advaith1 commented on src/lib/api/apiRequest.ts
> +  });
since rewrite is using this endpoint for non-discord users this shouldnt be typed as DiscordUser. however the backend's response objects seem to be inconsistent as this endpoint uses `_id` and guestLogin uses `id`

2023-08-18 00:34 UTC, advaith1 commented on src/components/Core/VirtualLists/MessagesListRenderer.tsx
> +export const MessagesListRenderer = ({
nit can this be changed to `MessageListRenderer`

2023-08-18 11:42 UTC, Yomanz commented on src/lib/api/apiRequest.ts
> +  });
This has been changed in the API, just not put live. `_id` wont show anywhere anymore, just `id`.

2023-08-18 17:02 UTC, Yomanz commented on src/components/Providers/UserProvider.tsx
> +      const token = localStorage.getItem('token');
Will be added in a future PR

2023-08-21 19:42 UTC, mason-rogers submitted a review, later dismissed

2023-08-21 23:29 UTC, advaith1 requested changes
![image](https://github.com/widgetbot-io/embed/assets/11778454/7b1912a0-7bfa-4314-acbc-ecb160aebc57)
can there be more space between the title and text? and can discord login be a prominent button like the mockups we had

also when logging out of a Discord account it opens the login modal, can that be removed? it doesn't do that for guest users

2023-08-21 23:29 UTC, advaith1 commented on src/components/Overlays/Modal/GuestFormModal/index.tsx
> +  }, [username, showGuestFormModal]);
I think this shouldn't be an effect https://react.dev/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state

2023-08-22 23:04 UTC, Yomanz approved these changes
LGTM

2023-08-22 23:25 UTC, advaith1 reviewed
works well! just some code comments and lets merge this 🚀

i think we'll update the discord login button later

2023-08-22 23:25 UTC, advaith1 commented on src/components/Overlays/Modal/GuestFormModal/GuestFormInput.tsx
> +);
is there a reason this is a separate component? seems to be unnecessary complexity when it can just be part of GuestForm

2023-08-22 23:25 UTC, advaith1 commented on src/lib/api/apiRequest.ts
> +  });
this should still be typed as a generic user not DiscordUser

2023-08-22 23:25 UTC, advaith1 commented on src/components/Header/styles.ts
>    paddingX: theme.space.sm.value,
what's going on with all of these? why do they error? is this something that will be fixed in the future or is it long-term

2023-08-23 11:20 UTC, mason-rogers commented on src/components/Header/styles.ts
>    paddingX: theme.space.sm.value,
They will be fixed in the future yes, I believe @JohnyTheCarrot discussed it with tyler already

2023-08-23 11:20 UTC, mason-rogers approved these changes

2023-08-23 19:32 UTC, tylergeorges commented on src/components/Overlays/Modal/GuestFormModal/GuestFormInput.tsx
> +);
I seperated them so GuestForm doesn't look as bloated and is easier to read

2023-08-31 21:23 UTC, mason-rogers approved these changes

2023-09-06 11:33 UTC, advaith1 approved these changes

2023-09-06 16:52 UTC, merged