NextJS Color Token and Font Weight fix
widgetbot-io/embed pull request #289
Opened 2023-08-11 19:44 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

This PR updates color tokens to discord's HSL colors and maps font weights to its correct font variant, e.g:
font-weight: 500 - gg sans medium font

2023-08-11 20:05 UTC, mason-rogers requested changes

2023-08-11 20:05 UTC, mason-rogers commented on src/components/Header/styles.ts
> +  height: 24
Do we use `24` in multiple places? Might be worth having a token, if it's a one-off I am fine with this

2023-08-11 20:05 UTC, mason-rogers commented on src/components/Sidebar/MembersSidebar/index.tsx
> +    <>
Why was this changed? If this component only returns a single element I'd lean more towards the previous version, rather than wrapping a single element in <></>

2023-08-11 20:05 UTC, mason-rogers commented on stitches.config.tsx
> +      // @ts-expect-error
What's the expected error? Can it be solved, if not can a comment about it be added

2023-08-11 20:19 UTC, tylergeorges commented on src/components/Header/styles.ts
> +  height: 24
This is the only place its used also discord hardcodes it to 24px as well

2023-08-11 20:21 UTC, tylergeorges commented on src/components/Sidebar/MembersSidebar/index.tsx
> +    <>
Oh whoops, I was trying to fix the text channel header border bottom getting hidden by the members list but I fixed it,

2023-08-11 21:07 UTC, tylergeorges commented on stitches.config.tsx
> +      // @ts-expect-error
Theres no way to properly type a color token and the type ScaleValue is the only type that wont throw a type error

2023-08-11 21:10 UTC, mason-rogers approved these changes

2023-08-12 15:14 UTC, JohnyTheCarrot requested changes

2023-08-12 15:14 UTC, JohnyTheCarrot commented on src/components/Shared/Icons/Buttons/IconButtonWrapper/styles.ts
>          // TODO: Find out why we need to access .value for it to work properly
remove this todo, since it's no longer applicable

2023-08-17 15:15 UTC, merged