Fix NextJS Message Renderer Resolve Functions
widgetbot-io/embed pull request #290
Opened 2023-08-14 19:53 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

Adds resolve functions to message renderer to resolve data such as the current guilds members, all roles for the guild, etc.

2023-08-16 19:22 UTC, Yomanz requested changes

2023-08-16 19:22 UTC, Yomanz commented on src/components/Providers/MessageRenderer.tsx
> +/* eslint-disable no-alert */
Why do you need this?

2023-08-16 19:22 UTC, Yomanz commented on src/hooks/useMessages.ts
> +      if (!mentions.length) continue;
Why not just `!mentions`

2023-08-16 19:22 UTC, Yomanz commented on src/state/stores/guild.ts
> +  members: undefined,
Can't this be set to `{}` rather than checking for it in the `addMember` action?

2023-08-16 19:23 UTC, advaith1 commented on src/hooks/useMessages.ts
> +      if (!mentions.length) continue;
!mentions.length checks if mentions is an empty array

2023-08-16 19:24 UTC, Yomanz commented on src/hooks/useMessages.ts
> +      if (!mentions.length) continue;
Ah ok

2023-08-21 19:43 UTC, mason-rogers commented
conflicts here @tylergeorges

2023-08-21 19:44 UTC, mason-rogers reviewed
@Yomanz has pointed out my only comment on this already, the rest looks good!

2023-08-29 19:07 UTC, Yomanz requested changes

2023-08-29 19:07 UTC, Yomanz commented on src/components/Providers/MessageRenderer.tsx
> +    if (!roles) return null;
This can be 1 if statement

2023-08-29 19:07 UTC, Yomanz commented on src/components/Providers/MessageRenderer.tsx
> +        fragment mention on Mention {
Fragment should be capitalized

2023-08-29 19:07 UTC, Yomanz commented on src/hooks/useMessages.ts
> +  let messageState: MessageState;
Why is this a let?

2023-08-29 19:07 UTC, Yomanz commented on src/util/convertToDiscord/convertUserToDiscord.ts
> +    avatar: ''
No avatar?

2023-08-29 19:59 UTC, Yomanz approved these changes

2023-08-30 13:46 UTC, mason-rogers approved these changes

2023-08-30 13:53 UTC, merged