NextJS Message Sending
widgetbot-io/embed pull request #293
Opened 2023-08-17 13:55 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

Based off of nextjs-auth branch allows authenticated users to send messages 

Resolves FR-75

2023-08-21 19:57 UTC, mason-rogers requested changes

2023-08-21 19:57 UTC, mason-rogers commented on src/components/Core/TextChannelContainer/MessageContainer.tsx
> +  const fetchMore = useCallback(
this function should be a part of useMessages really

2023-08-21 19:57 UTC, mason-rogers commented on src/components/Core/TextChannelContainer/TextBox/TextBoxInput.tsx
>    const handleKeyDown = (e: React.KeyboardEvent) => {
A switch on `key` would be better for this rather than a lot of if statements

2023-08-21 19:57 UTC, mason-rogers commented on src/components/Core/TextChannelContainer/TextBox/TextBoxInput.tsx
> +      const enterNewLine = key === 'Enter' && modifierKeys.Shift.isHolding;
This is inside key === 'Enter', so you dont need to check it again

2023-08-21 19:57 UTC, mason-rogers commented on src/components/Overlays/Modal/Popout/ThreadsPopout/ChannelThreads.tsx
> +import { TChannel } from 'types/guild.types';
Do we do the `T` prefix anywhere else?

2023-08-21 19:57 UTC, mason-rogers commented on src/hooks/useMessageSubscription.ts
> +        if (!(newMessage.flags ?? 0 & (1 << 4))) {
Could this be improved in any way to be more readable?

2023-08-21 19:57 UTC, mason-rogers commented on src/util/getOptimisticIndex.ts
> +  return messages.findIndex(
```suggestion
  return messages.findIndex(m =>
```

Use braces instead with a return statement, it'll be more readable

2023-08-21 22:04 UTC, tylergeorges commented on src/components/Overlays/Modal/Popout/ThreadsPopout/ChannelThreads.tsx
> +import { TChannel } from 'types/guild.types';
They are extended types used to resolved type errors, they are now renamed to APIDiscordChannel, GqlChannel, and GqlThread

2023-08-22 23:08 UTC, Yomanz approved these changes
just a few changes needed, good stuff.

2023-08-22 23:08 UTC, Yomanz commented on src/components/Core/TextChannelContainer/TextBox/index.tsx
> +import { useAppRouter } from '../../../../hooks/useAppRouter';
The only import without a @?

2023-08-22 23:08 UTC, Yomanz commented on src/util/convertToDiscord/convertMessageToDiscord.ts
> +    bot: message.isGuest,
Still need to check author.bot as far as I'm aware.

2023-08-22 23:10 UTC, advaith1 commented on src/util/convertToDiscord/convertMessageToDiscord.ts
> +    bot: message.isGuest,
`bot` should only check author.bot, guest messages should have a GUEST tag

2023-08-22 23:47 UTC, Yomanz commented on src/util/convertToDiscord/convertMessageToDiscord.ts
> +    bot: message.isGuest,
> do guests get the guest tag through isGuest? Also are users under the "Guest" Provider the only ones that get bot tags?

No, anyone who sends a message via WidgetBot I believe is the current logic.

2023-08-23 22:52 UTC, mason-rogers requested changes

2023-08-23 22:52 UTC, mason-rogers commented on src/components/Core/TextChannelContainer/TextBox/TextBoxInput.tsx
> +  const placeholderOptions =
This looks unreadable tbh

```
const placeholderOptions = canSend && isAuthed
      ? {CHANNEL: channelIsThread ? currentThread?.name : currentChannel?.name}
      : {};
```

2023-08-28 12:08 UTC, Yomanz requested changes
a few changes needed

2023-08-28 12:08 UTC, Yomanz commented on package.json
>      "@urql/exchange-auth": "^2.1.6",
Lets get rid of these old deps

2023-08-28 12:08 UTC, Yomanz commented on src/components/Providers/GuildProvider.tsx
> +const annoucmentChannelFragment = graphql(`
Spelling mistake

2023-08-28 12:08 UTC, Yomanz commented on src/types/messages.types.ts
> +export interface MessagesQuery {
This should be generated

2023-08-28 12:08 UTC, Yomanz commented on src/util/groupMessages.ts
>  /* eslint-disable no-plusplus */
Use += 1?

2023-08-28 12:24 UTC, advaith1 reviewed
some small comments, also auth doesn't seem to work properly (see Discord thread)

2023-08-28 12:24 UTC, advaith1 commented on src/hooks/messagesQuery/index.ts
>  export const messagesQuery = graphql(`
can these use `` gql` `` instead of `` graphql(` ``? that supports syntax highlighting

2023-08-28 12:24 UTC, advaith1 commented on src/state/stores/guild.ts
> +    // const sortedChannels = payload.sort((a, b) => positionChannel(a) - positionChannel(b));
is this comment intentional?

2023-08-28 12:24 UTC, advaith1 commented on src/types/user.types.ts
> +  _id: string;
didn't we move away from using `_id`?

2023-08-28 15:15 UTC, tylergeorges commented on src/hooks/messagesQuery/index.ts
>  export const messagesQuery = graphql(`
gql`` doesn't have type safety when using useQuery hook

2023-08-28 19:15 UTC, mason-rogers approved these changes
I'm happy with this other than the last changes advaith mentioned. Good work

2023-08-31 21:22 UTC, mason-rogers requested changes

2023-08-31 21:22 UTC, mason-rogers commented on src/components/Core/VirtualLists/MessageListRenderer.tsx
> +    const followOutput = (isAtBottom: boolean) => {
This method is pointless, see below comment

2023-08-31 21:22 UTC, mason-rogers commented on src/components/Core/VirtualLists/MessageListRenderer.tsx
>            followOutput={followOutput}
```suggestion
          followOutput={() => isAtBottom}
```

2023-09-06 17:19 UTC, mason-rogers approved these changes
LGTM, lets get this merged asap

2023-09-06 19:51 UTC, Yomanz approved these changes
LGTM

2023-09-06 19:51 UTC, Yomanz commented
Needs a review from @advaith1, then it can be merged!

2023-09-07 01:29 UTC, advaith1 commented on src/components/Core/TextChannelContainer/TextBox/TextBoxInput.tsx
>        }
is this necessary?

2023-09-07 01:29 UTC, advaith1 commented on src/components/Sidebar/ChannelsSidebar/ChannelsFooter/styles.ts
>    }
can't this be combined into one selector?

2023-09-07 11:48 UTC, tylergeorges commented on src/components/Core/TextChannelContainer/TextBox/TextBoxInput.tsx
>        }
Throws an eslint error if no default case

2023-09-08 03:30 UTC, advaith1 approved these changes
seems good except for broken avatars on sent msgs

2023-09-08 09:41 UTC, merged