NextJS Pinned Messages Modal
widgetbot-io/embed pull request #307
Opened 2023-08-31 17:45 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

This PR adds a pinned messages modal 

Resolves FR-90

2023-08-31 21:17 UTC, mason-rogers requested changes

2023-08-31 21:17 UTC, mason-rogers commented on src/components/Overlays/Modal/Popout/PinnedMessagesPopout/NoPins.tsx
> +  const translate = useTranslation();
```suggestion
  const { t } = useTranslation();
```

2023-08-31 21:17 UTC, mason-rogers commented on src/components/Overlays/Modal/Popout/PinnedMessagesPopout/PinnedMessage.tsx
> +    <Message message={message} isFirstMessage thread={!!message.thread} />
This might not necessarily be related to this pr but something I noticed, if `thread` takes a boolean I think `isThread` is a better name for it, which matches the `isFirstMessage` boolean

2023-08-31 21:17 UTC, mason-rogers commented on src/components/Overlays/Modal/Popout/PinnedMessagesPopout/index.tsx
> +  const translate = useTranslation();
```suggestion
  const { t } = useTranslation();
```

2023-08-31 21:17 UTC, mason-rogers commented on src/components/Overlays/Modal/Popout/PinnedMessagesPopout/index.tsx
> +          {pinnedMessages.length === 0 ? (
```suggestion
          {!pinnedMessages.length ? (
```

2023-08-31 21:17 UTC, mason-rogers commented on src/hooks/useMessages.ts
> +            if (!draft.channelV2 || !('messageBunch' in draft.channelV2)) return draft;
```suggestion
            if (!draft.channelV2?.messageBunch) return draft;
```

2023-09-01 12:11 UTC, tylergeorges commented on src/components/Overlays/Modal/Popout/PinnedMessagesPopout/PinnedMessage.tsx
> +    <Message message={message} isFirstMessage thread={!!message.thread} />
Yeah i agree, but thats a message renderer problem, i can add an additional isThread prop though and pass message.thread like that

2023-09-01 12:17 UTC, advaith1 requested changes
The modal should close when the user clicks out of it
also, this has too much padding, and it shouldnt have the "older threads" header
![image](https://github.com/widgetbot-io/embed/assets/11778454/8b7dc98b-1a67-4bd4-9098-6da64123ae1d)
is the lack of message data here due to staging backend being broken?

also why is the no-pins image in `message-renderer-assets` when it isn't being used by message renderer?

2023-09-01 20:22 UTC, Yomanz approved these changes

2023-09-01 20:24 UTC, Yomanz requested changes
You can currently overlap threads and pinned messages modal.

2023-09-10 01:08 UTC, advaith1 approved these changes

2023-09-17 13:58 UTC, mason-rogers approved these changes

2023-09-17 17:00 UTC, Yomanz approved these changes

2023-09-19 12:34 UTC, merged