NextJS Channel Header Alignment Fix
widgetbot-io/embed pull request #310
Opened 2023-09-06 20:30 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

Fixes channel header alignment issues 

Resolves FR-97

2023-09-10 01:04 UTC, advaith1 requested changes
[icon-stage-channel.svg](https://github.com/widgetbot-io/embed/pull/310/files#diff-a42eef5ff5639369d6dca3547663026c61f7b817a844fe197524342798477db2) was changed from the stage icon to the text channel icon

2023-09-14 10:54 UTC, Yomanz commented
Conflicts

2023-09-17 13:59 UTC, mason-rogers commented
@tylergeorges bump ^ conflicts here

2023-09-17 14:01 UTC, mason-rogers approved these changes

2023-09-18 21:16 UTC, merged