NextJS Message Renderer Update
widgetbot-io/embed pull request #315
Opened 2023-09-06 22:35 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

2023-09-08 09:43 UTC, Yomanz approved these changes

2023-09-08 09:44 UTC, JohnyTheCarrot approved these changes

2023-09-10 01:13 UTC, advaith1 requested changes

2023-09-10 01:13 UTC, advaith1 commented on src/components/Providers/MessageRenderer.tsx
> +      flags: RoleFlags.InPrompt,
why is this flag always set? it's not relevant to messages anyway, this can just be 0

2023-09-11 14:31 UTC, tylergeorges commented on src/components/Providers/MessageRenderer.tsx
> +      flags: RoleFlags.InPrompt,
the new renderer requires new discord api types and APIRole requires flag field and 0 isn't assignable to flags field

2023-09-12 14:41 UTC, Yomanz approved these changes

2023-09-12 14:42 UTC, merged