NextJS Modal System
widgetbot-io/embed pull request #318
Opened 2023-09-11 20:58 UTC by tylergeorges

**Please describe the changes this PR makes and why it should be merged:**

Modal system that waits for any modal transitions/animations before adding/removing modal from DOM

Resolves FR-68

2023-09-17 14:01 UTC, mason-rogers commented
conflicts @tylergeorges

2023-09-18 01:21 UTC, advaith1 requested changes
also can the commented-out imports be removed, and can the close animation be faster

2023-09-18 01:21 UTC, advaith1 commented on src/components/Overlays/Modal/GuestFormModal/index.tsx
> +      {/*  @ts-expect-error */}
what's going on here? if this is staying it needs an explanation in the comment (at all occurrences)

2023-09-25 21:19 UTC, mason-rogers approved these changes

2023-09-25 21:35 UTC, Yomanz requested changes
I'll finish reviewing after the stuff is moved to use enums 👍

2023-09-25 21:35 UTC, Yomanz commented on src/components/Core/TextChannelContainer/TextBox/TextBoxInput.tsx
> +        show('guest-form');
Can we move this to an enum.

2023-09-25 21:35 UTC, Yomanz commented on src/components/Header/TextChannelHeader/index.tsx
> +    addToDOM('channel-topic');
enum?

2023-09-25 21:35 UTC, Yomanz commented on src/components/Overlays/Modal/GuestFormModal/GuestForm.tsx
> +    hide('guest-form');
enum?

2023-09-25 21:35 UTC, Yomanz commented on src/components/Overlays/Modal/Popout/ThreadsPopout/ChannelThreads.tsx
> +    addToDOM('thread-panel');
enum?

2023-09-25 21:35 UTC, Yomanz commented on src/components/Providers/MessageRenderer.tsx
> +      addToDOM('thread-panel');
enum?

2023-09-25 21:35 UTC, Yomanz commented on src/components/Providers/ModalProvider/index.tsx
> +  const modalStateContext = useMemo(
enum for this whole func?

2023-09-25 21:35 UTC, Yomanz commented on src/components/Providers/ModalProvider/modalReducer.ts
> +  switch (action.type) {
enum for this func?

2023-09-25 21:35 UTC, Yomanz commented on src/components/Providers/ModalProvider/modals.ts
> +registerModal('channel-topic', ChannelTopicModal);
enum?

2023-09-25 21:35 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +  'channel-topic': {
enum?

2023-09-25 21:35 UTC, Yomanz commented on src/components/Shared/Icons/Buttons/ThreadsPanelButton/index.tsx
> +    addToDOM('thread-panel');
im going to stop leaving enum comments now

2023-09-26 15:15 UTC, Yomanz requested changes
Still a few changes needed

2023-09-26 15:15 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +type Ids = `${ModalId}`;
What is this?

2023-09-26 15:15 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +export type BaseModalData<ModalIds extends string = Ids> = {
Why is there a generic here?

2023-09-26 15:15 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +  [Id in ModalIds]: {
Cant this just be `Id in ModalId`?

2023-09-26 15:15 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +    Comp: ModalElement | null;
Does this need to be null?

2023-09-26 15:15 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +export interface ModalData extends Omit<BaseModalData[Ids], 'ModalElement'> {
Why `[Ids]`?

2023-09-26 15:15 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +  'channel-topic': {
You're still not using the enums here, the only place these strings should be are in the enum

2023-09-26 15:15 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +    Comp: null as ModalElement | null,
This should be undefined, refer to the style docs.

2023-09-26 15:15 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +    isOpen: false as boolean
Why are you casting this?

2023-09-26 16:45 UTC, tylergeorges commented on src/components/Providers/ModalProvider/registeredModals.ts
> +export interface ModalData extends Omit<BaseModalData[Ids], 'ModalElement'> {
Because we need to access the Modal Data which is nested under an object

2023-09-26 17:07 UTC, Yomanz requested changes

2023-09-26 17:07 UTC, Yomanz commented on src/components/Sidebar/ChannelsSidebar/ChannelsFooter/ChannelsFooterLoginButton.tsx
> +import * as Styles from '@components/Sidebar/ChannelsSidebar/ChannelsFooter/styles';
Why is this such a long import

2023-09-26 17:07 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +export type RegisteredModals = typeof registeredModals;
This is backwards.
You should have the type defined above the `const` and then assign the `const` to the type.
Ideally anything exported for public use should have a type assigned to it.

`Record<ModalId, Interface>`

2023-09-26 17:07 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +  [Id in ModalId]: {
You still need to move this out to an interface.

2023-09-26 17:07 UTC, Yomanz commented on src/components/Providers/ModalProvider/registeredModals.ts
> +  [Id in ModalId]: {
Also, isn't this the equivalent of `Record<ModalId, interface>`

2023-09-26 17:32 UTC, tylergeorges commented on src/components/Providers/ModalProvider/registeredModals.ts
> +  [Id in ModalId]: {
I set it up this way so it type checks to make sure the key of the object and id in the object are the same, if I try to do it with an interface it errors

![image](https://github.com/widgetbot-io/embed/assets/94828874/6058bd2e-eeb7-4390-8273-996e12314ef5)

If it was a record I dont get the same type safety 
![image](https://github.com/widgetbot-io/embed/assets/94828874/8929a739-eced-4695-9cd0-9b8b729dcb66)

Errors: 
![image](https://github.com/widgetbot-io/embed/assets/94828874/f0f6cd97-2115-4143-972f-58f34528ddec)

No Errors
![image](https://github.com/widgetbot-io/embed/assets/94828874/ca2853a4-4b79-4e29-832f-2dbe6d7c177e)

2023-10-01 19:16 UTC, Yomanz approved these changes

2023-10-02 15:53 UTC, JohnyTheCarrot requested changes

2023-10-02 15:53 UTC, JohnyTheCarrot commented on src/components/Overlays/Modal/InformationModal/index.tsx
> +
These extra blank lines seem unnecessary.

2023-10-02 15:53 UTC, JohnyTheCarrot commented on src/components/Overlays/Modal/index.tsx
> +  modalId: ModalId;
```tsx
interface ModalProps extends Omit<ModalHeaderContainerProps, 'children'> {
  children({ closeModal }: { closeModal(): void }): ReactNode;
  title: string;
  disableBackdrop?: boolean;
  modalId: ModalId;
}
```

2023-10-02 15:53 UTC, JohnyTheCarrot commented on src/types/modal.types.ts
> +};
```suggestion
export interface ModalData extends Omit<RegisteredModals[ModalId], 'Component'> {
  Component: ModalElement;
};
```

2023-10-02 19:48 UTC, mason-rogers approved these changes

2023-10-02 19:48 UTC, mason-rogers commented
conflicts here @tylergeorges

2023-10-03 15:21 UTC, mason-rogers approved these changes

2023-10-03 15:21 UTC, merged