[FR-113] NextJS Message Action Buttons
widgetbot-io/embed pull request #319
Opened 2023-09-12 14:47 UTC by tylergeorges

This PR adds message actions such as:

- Speak Message
- Copy Message ID
- Copy Message Link

(Delete message action will be implemented in separate PR)

Resolves FR-113

2023-09-15 01:18 UTC, advaith1 requested changes
* buttons should use cursor: pointer
* buttons should move down on click like in Discord
* spoken text includes `message.speak.said` instead of the correct string

first two might be message renderer issues

2023-09-18 21:52 UTC, tylergeorges commented
@advaith1 
- for cursor pointer i fixed it by setting cursor: pointer as default for buttons

- message buttons moving down on click is a message renderer thing

- fixed the speak message not resolving localized string

2023-09-19 12:40 UTC, JohnyTheCarrot requested changes

2023-09-19 12:40 UTC, JohnyTheCarrot commented on src/components/Providers/MessageRenderer.tsx
> +      ? `${t('message.speak.repliedto')} ${message.referenced_message.author.username}`
This isn't the way. The location of the username in the string should be localizable too, different languages put them in different places. Example: "{x} replied to {y}" -> "{x} heeft op {y} geantwoord" (not the same string in the example)

2023-09-20 15:21 UTC, JohnyTheCarrot approved these changes

2023-09-21 15:57 UTC, merged