NextJS Guest Tag
widgetbot-io/embed pull request #321
Opened 2023-09-12 17:35 UTC by tylergeorges

Resolves FR-84

2023-09-15 01:29 UTC, advaith1 requested changes

2023-09-15 01:29 UTC, advaith1 commented on src/components/Providers/MessageRenderer.tsx
> +  > | null => {
this isn't necessary, ts automatically gets the correct return type and it works
```suggestion
  }: GetChatBadgeArgs) => {
```

2023-09-15 01:29 UTC, advaith1 commented on src/components/Providers/MessageRenderer.tsx
> +      return <TagWrapper>GUEST</TagWrapper>;
this should be a localized string (and ideally it should have `text-transform: uppercase` in the css so the string can be "Guest")

2023-09-17 13:21 UTC, mason-rogers reviewed
LGTM other than the comments advaith made, will approve once fixed

2023-09-18 19:22 UTC, advaith1 approved these changes

2023-09-18 19:29 UTC, Yomanz approved these changes

2023-09-18 19:30 UTC, merged