[FR-115] NextJS Expandable Images
widgetbot-io/embed pull request #329
Opened 2023-09-19 13:02 UTC by tylergeorges

2023-09-19 13:40 UTC, Yomanz requested changes
The animation is way too slow and it's responsiveness isn't fantastic but not sure what you can do about that, the animation needs to be sped up though

2023-09-25 21:31 UTC, Yomanz requested changes

2023-09-25 21:31 UTC, Yomanz commented on src/components/Overlays/Modal/ImageModal/index.tsx
> +            width={width as number}
Why do you have to cast them, what are they actually passed as?

2023-09-25 21:31 UTC, Yomanz commented on src/components/Overlays/Modal/ImageModal/index.tsx
> +            height={height as number}
See above

2023-09-25 21:31 UTC, Yomanz commented on src/components/Providers/MessageRenderer.tsx
> +    setImageModalData(image as APIEmbed['image']);
Is this a safe cast?

2023-09-26 00:23 UTC, advaith1 requested changes
also the background dim needs to go away faster when the image is closed

2023-09-26 00:23 UTC, advaith1 commented on src/components/Overlays/Modal/ImageModal/index.tsx
> +  const isOpen = !!toggled;
isn't toggled always a boolean? why is this other variable needed, is `isOpen` not always equal to `toggled`?

2023-09-26 00:23 UTC, advaith1 commented on src/components/Overlays/Modal/ImageModal/index.tsx
> +  if (!imageModalData) return <></>;
```suggestion
  if (!imageModalData) return null;
```

2023-10-02 12:31 UTC, Yomanz approved these changes

2023-10-02 19:43 UTC, mason-rogers commented
conflicts here @tylergeorges

2023-10-02 19:46 UTC, mason-rogers approved these changes

2023-10-16 14:03 UTC, merged