[FR-126] NextJS Message Input Spacing Fix
widgetbot-io/embed pull request #331
Opened 2023-09-20 13:45 UTC by tylergeorges

2023-09-21 12:54 UTC, Yomanz approved these changes

2023-09-23 01:22 UTC, advaith1 requested changes
* the height is wrong - Discord's textbox height is 44px, this box is 37.33px when not logged in and 40px when logged in (it should at least not change)
* why is the input a div and not a textarea? the hacky placeholder div instead of using a proper textarea placeholder field has some issues (after adding a newline and deleting it, the placeholder does not display unless i hit backspace an extra time)

2023-09-25 14:48 UTC, tylergeorges commented
> * the height is wrong - Discord's textbox height is 44px, this box is 37.33px when not logged in and 40px when logged in (it should at least not change)
> 
>     * why is the input a div and not a textarea? the hacky placeholder div instead of using a proper textarea placeholder field has some issues (after adding a newline and deleting it, the placeholder does not display unless i hit backspace an extra time)

the reason its in a content editable div is if in the future we want to support markdown/insert emojis as images like how discord has it

2023-10-02 19:43 UTC, mason-rogers approved these changes

2023-10-03 16:49 UTC, merged