[FR-88] NextJS Bot Avatar Resolve Fix
widgetbot-io/embed pull request #337
Opened 2023-09-25 15:44 UTC by tylergeorges

2023-09-25 21:30 UTC, Yomanz requested changes

2023-09-25 21:30 UTC, Yomanz commented on src/util/convertToDiscord/convertField.ts
> +    const userId = message.author.id.includes('-')
What are you checking here?

2023-09-25 21:30 UTC, Yomanz commented on src/components/Providers/MessageRenderer.tsx
> +  const getUserAvatar = (user: APIUser): string | null => user.avatar;
Can't you just do `user.avatar` in the code?

2023-09-25 21:30 UTC, Yomanz commented on src/util/convertToDiscord/getAvatarId.ts
> +  return avatarId?.includes('robohash') ? generateSnowflake() : avatarId;
As far as I'm aware our avatar IDs dont contain the word "robohash"?

2023-09-25 21:30 UTC, Yomanz commented on src/util/convertToDiscord/getAvatarId.ts
> +  return id?.includes('robohash') ? generateSnowflake() : id;
See above comment

2023-09-25 23:13 UTC, advaith1 commented on src/util/convertToDiscord/getAvatarId.ts
> +  return avatarId?.includes('robohash') ? generateSnowflake() : avatarId;
robohash is in the URLs but we probably shouldn't rely on that?

2023-09-26 14:47 UTC, tylergeorges commented on src/util/convertToDiscord/convertField.ts
> +    const userId = message.author.id.includes('-')
created guest accounts have hyphens in the ID and theres a bug in the message renderer where if the users ID isn't in snowflake format it errors/crashes

2023-09-26 15:02 UTC, tylergeorges commented on src/components/Providers/MessageRenderer.tsx
> +  const getUserAvatar = (user: APIUser): string | null => user.avatar;
This is for overriding the Message Renderer's avatarUrl because it creates a avatarUrl from user ID and avatar ID which is an issue for created guest accounts

2023-09-26 15:06 UTC, tylergeorges commented on src/util/convertToDiscord/getAvatarId.ts
> +  return avatarId?.includes('robohash') ? generateSnowflake() : avatarId;
It's apart of the url, but avatar fields don't rely on this anymore because of the authorUrlOverride prop on the Message Renderer

2023-09-26 23:25 UTC, mason-rogers requested changes

2023-09-26 23:25 UTC, mason-rogers commented on src/util/convertToDiscord/convertField.ts
> +    const userId = message.author.id.includes('-')
Can we rather introduce a isUuid method, which validates against a regex - this is an ugly way of detecting if a uuid or not

2023-09-26 23:25 UTC, mason-rogers commented on src/util/convertToDiscord/convertField.ts
> +    console.log();
```suggestion
```

2023-09-27 18:15 UTC, Yomanz approved these changes

2023-10-02 19:42 UTC, mason-rogers approved these changes

2023-10-03 15:43 UTC, merged