[FR-103] NextJS Loading Box Fix
widgetbot-io/embed pull request #338
Opened 2023-09-25 16:06 UTC by tylergeorges

2023-09-26 23:23 UTC, mason-rogers requested changes

2023-09-26 23:23 UTC, mason-rogers commented on src/components/Core/VirtualLists/listComponents.tsx
> +  context?: { isAllMessagesFetched: boolean; isFetching: boolean };
Can this be split into an interface, nested types looks pretty ugly imo

2023-09-26 23:23 UTC, mason-rogers commented on src/components/Core/VirtualLists/listComponents.tsx
> +export const listComponents = { Header: FetchingDataSpinner } as ListComponents;
Why does this need to be casted and not just typed?

2023-10-02 19:42 UTC, mason-rogers approved these changes

2024-01-17 23:52 UTC, mason-rogers approved these changes

2024-01-19 14:05 UTC, Yomanz approved these changes

2024-01-19 15:29 UTC, merged