[FR-140] NextJS Resolving Author Fix
widgetbot-io/embed pull request #339
Opened 2023-09-25 17:21 UTC by tylergeorges

Fixes bug where resolving an author sometimes returns wrong author and an author's roles/nick color doesn't resolve

2023-09-25 21:19 UTC, mason-rogers requested changes

2023-09-25 21:19 UTC, mason-rogers commented on src/components/Providers/MessageRenderer.tsx
> +    const isGuest = user.isGuest || (user.bot && user.discriminator === '0000');
I feel like ive seen this in a few places before, maybe we should just make a userIsGuest helper method somewhere

2023-09-25 21:19 UTC, mason-rogers commented on src/util/groupMessages.ts
> +  if (recentMessage.author.username === 'keras09') {
whats this?

2023-10-02 16:03 UTC, JohnyTheCarrot requested changes

2023-10-02 16:03 UTC, JohnyTheCarrot commented on src/util/userIsGuest.ts
> +  user.isGuest || (user?.bot && user.discriminator === '0000') || false; // Add false fallback to make function return type boolean
```suggestion
export function userIsGuest(user: ExtendedAPIUser) {
  const userIsBot = user.bot ?? false;

  return user.isGuest || (userIsBot && user.discriminator === '0000');
}
```

2023-10-02 19:39 UTC, mason-rogers requested changes
Looks fine other than the small things suggested.

General consensus of this is that if you're only defining something to use it once, and it looks clean just doing it inline still then I'd say just inline it.

Good example:
```js
if (userIsGuest(user)) {
 //
}
```

Bad example:
```js
if (user.isGuest || (user?.bot && user.discriminator === '0000')) {
 //
}
```

2023-10-02 19:39 UTC, mason-rogers commented on src/components/Providers/MessageRenderer.tsx
> +    if (isGuest) {
```suggestion
    if (userIsGuest(user)) {
```

2023-10-02 19:39 UTC, mason-rogers commented on src/components/Providers/MessageRenderer.tsx
> +    const queryId = isGuest ? `${baseQueryId}:${user.username}` : baseQueryId;
```suggestion
    const queryId = userIsGuest(user) ? `${baseQueryId}:${user.username}` : baseQueryId;
```

2023-10-02 19:39 UTC, mason-rogers commented on src/components/Providers/MessageRenderer.tsx
> +    const isGuest = userIsGuest(user);
```suggestion
```

2023-10-02 19:39 UTC, mason-rogers commented on src/util/convertToDiscord/convertUserToDiscord.ts
> +    avatar: avatarId
```suggestion
    avatar: getAvatarId(user.avatarUrl)
```

2023-10-02 19:39 UTC, mason-rogers commented on src/util/convertToDiscord/convertUserToDiscord.ts
> +  const avatarId = getAvatarId(user.avatarUrl);
```suggestion
```

2023-10-12 13:44 UTC, Yomanz approved these changes

2023-10-16 14:03 UTC, mason-rogers approved these changes

2023-10-16 14:22 UTC, mason-rogers approved these changes

2023-10-16 14:22 UTC, merged