[FR-133] NextJS Context Menu Persisting Fix
widgetbot-io/embed pull request #340
Opened 2023-09-25 17:27 UTC by tylergeorges

2023-09-25 21:19 UTC, mason-rogers approved these changes

2023-09-25 21:27 UTC, Yomanz requested changes

2023-09-25 21:27 UTC, Yomanz commented on src/hooks/useClickOutside.ts
> +  includeElement?: HTMLElement | null;
This upsets me greatly, is there a reason for this (having both undefined and null).

2023-09-26 14:31 UTC, tylergeorges commented on src/hooks/useClickOutside.ts
> +  includeElement?: HTMLElement | null;
For the Popout Modal the includeElement is a ref for a div that wraps an icon button, and useRef needs null as the initial value or else the wrapper div throws an error. 

So includeElement can either not be defined at all, be null or it could be an element, I can cast the includeElement wrapper div to HTMLElement | undefined if that's better

2023-09-26 16:57 UTC, Yomanz commented on src/hooks/useClickOutside.ts
> +  includeElement?: HTMLElement | null;
Does it make a difference whether it's not defined at all or null?

2023-09-27 18:16 UTC, Yomanz approved these changes

2023-09-27 18:18 UTC, merged