[FR-66] NextJS Status Modals
widgetbot-io/embed pull request #343
Opened 2023-10-09 14:33 UTC by tylergeorges

2023-10-09 14:44 UTC, mason-rogers commented on src/components/Overlays/Modal/styles.ts
> +      zoomIn: {},
Does this actually do anything? I guess having the zoomIn key is enough?

2023-10-09 14:44 UTC, mason-rogers commented on stitches.config.tsx
> +      info: '$accent'
I assume we cant use typed tokens here?

2023-10-09 17:21 UTC, tylergeorges commented on stitches.config.tsx
> +      info: '$accent'
If you mean for the info token that won't be possible since it needs to reference another token in the same object

2023-10-09 17:24 UTC, tylergeorges commented on src/components/Overlays/Modal/styles.ts
> +      zoomIn: {},
It's used so i can just reuse the Modal component for the Status Modal and use the slide animation's for it, unless you mean just make zoom animations the default and keep slide animation variants?

2023-10-10 09:49 UTC, advaith1 requested changes
code mostly lgtm, ui should be improved though

![image](https://github.com/widgetbot-io/embed/assets/11778454/f245cb67-2b94-4263-9993-0c9c638e016d)

also can the slide out animation go to the right

2023-10-10 09:49 UTC, advaith1 commented on src/components/Providers/ModalProvider/index.tsx
> +/* eslint-disable no-plusplus */
why is this here?

2023-10-10 09:49 UTC, advaith1 commented on src/components/Providers/ModalProvider/modalReducer.ts
> +          // Cast ModalEleemnt because modal component should be defined when this is called
```suggestion
          // Cast ModalElement because modal component should be defined when this is called
```

2023-10-10 09:49 UTC, advaith1 commented on src/types/modal.types.ts
> +// export type ModalProps = React.ComponentProps<any>;
is this comment staying?

2023-10-10 09:49 UTC, advaith1 commented on src/components/Overlays/Modal/InformationModal/StatusModal/index.tsx
> +  modalId: any;
does this need to be any?

2023-10-17 13:46 UTC, mason-rogers approved these changes

2023-10-19 10:49 UTC, advaith1 approved these changes

2023-10-19 15:53 UTC, merged