[FR-148] NextJS Forums
widgetbot-io/embed pull request #344
Opened 2023-10-12 16:02 UTC by tylergeorges

2023-10-22 19:07 UTC, mason-rogers requested changes

2023-10-22 19:07 UTC, mason-rogers commented on src/hooks/messagesQuery/index.ts
> +          messageBunch(limit: 1) {
I assume the two messageBunch queries are to fetch the first & also most recent message?

2023-10-22 19:07 UTC, mason-rogers commented on src/util/short.ts
> +const minute = 6e4;
What unit is this value supposed to be? I'd prefer if these were defined in a more readable way

e.g `const minute = 60 * 1000`

2023-10-22 20:09 UTC, advaith1 commented on src/hooks/messagesQuery/index.ts
> +          messageBunch(limit: 1) {
yeah this is how the current implementation works (though backend ignores the limit param)

2023-11-02 16:01 UTC, mason-rogers reviewed
Looks good! Just one question

2023-11-22 15:33 UTC, mason-rogers approved these changes

2023-12-19 09:52 UTC, advaith1 requested changes
opening forum threads seems to not work

![image](https://github.com/widgetbot-io/embed/assets/11778454/d90556b1-b4f5-4bfa-9f22-ca8f06fa5f0b)

2024-01-04 22:56 UTC, advaith1 requested changes

2024-01-04 22:56 UTC, advaith1 commented on src/components/Core/TextChannelContainer/styles.ts
> +  // maxHeight: '50vh',
commented out code

2024-01-05 10:41 UTC, advaith1 requested changes

2024-01-05 10:41 UTC, advaith1 commented on src/components/Header/ForumHeader/index.tsx
> +        <Icons icon="FourmChannelIcon" color="channel" marginX="xs" size="sm" />
typo (also needs to be fixed elsewhere

2024-01-09 02:26 UTC, advaith1 approved these changes

2024-01-09 17:36 UTC, merged