[FR-170] NextJS Add Modal Popout to Modal System
widgetbot-io/embed pull request #356
Opened 2023-11-07 18:15 UTC by tylergeorges

2023-11-20 17:34 UTC, Yomanz requested changes

2023-11-20 17:34 UTC, Yomanz commented on src/components/Providers/ModalProvider/addNotification.ts
> +  addModal(ModalId.StatusModal, { level, message, title, modalId }, modalId);
Why are you passing modalId twice?

2023-11-21 15:53 UTC, tylergeorges commented on src/components/Providers/ModalProvider/addNotification.ts
> +  addModal(ModalId.StatusModal, { level, message, title, modalId }, modalId);
the first time its passed as a prop to StatusModal component and the second time its passed as an Id override since status modals id's get uniquely generated

2023-11-30 15:45 UTC, mason-rogers commented on src/components/Providers/ModalProvider/addNotification.ts
> +  addModal(ModalId.StatusModal, { level, message, title, modalId }, modalId);
@tylergeorges are they the same value though? I feel like this can be merged into a single thing, I'm not sure I understand what you mean as to why you need two

2023-11-30 16:34 UTC, tylergeorges commented on src/components/Providers/ModalProvider/addNotification.ts
> +  addModal(ModalId.StatusModal, { level, message, title, modalId }, modalId);
@mason-rogers I merged them in newest commit

2023-12-04 15:33 UTC, merged