[FR-31] NextJS Emoji Picker
widgetbot-io/embed pull request #360
Opened 2023-11-27 15:52 UTC by tylergeorges

2023-12-19 09:54 UTC, advaith1 requested changes
deploy preview crashes on load
![image](https://github.com/widgetbot-io/embed/assets/11778454/bb318198-3926-4dfb-8d37-86dec58d12a3)

also there are merge conflicts

2024-01-04 23:01 UTC, advaith1 requested changes
The images don't have a fixed width and height so they reflow as they load. this shouldn't happen

https://github.com/widgetbot-io/embed/assets/11778454/7da92882-accc-45f2-9e69-8331d4f78ffa

also, the corners aren't rounded, and clicking an emoji does not close the emoji picker. (we can support shift+clicking emojis to keep the picker open, but normal clicking should close the picker.)

2024-01-12 10:05 UTC, advaith1 approved these changes

2024-01-15 10:45 UTC, mason-rogers commented on src/components/Core/TextChannelContainer/TextBox/TextBoxInput.tsx
> +  const modifierKeysRef = useRef<ModifierKeys>({
This might be nice abstracted into a useModifierKeys, if we ever need to/already re-use this

2024-01-15 10:45 UTC, mason-rogers commented on src/components/Overlays/Modal/Popout/index.tsx
> +  const windowIsMobile = useMediaQuery('screen and (max-width: 450px)');
this is unrelated to this PR - but I feel like I see this a lot and it might just be nicer to have defined queries somewhere/rename the method to useIsMobile or something

Just saves updating a million places if we ever need to update it and also will appear cleaner

2024-01-15 10:45 UTC, mason-rogers commented on src/components/Providers/GuildProvider.tsx
> +import { useTranslation } from 'react-i18next';
import order

2024-01-15 10:45 UTC, mason-rogers commented on src/components/Shared/Icons/index.tsx
> +  // Emojis
Is this going to collide with https://github.com/widgetbot-io/embed/pull/375 as Tuur states custom icons should be prefixed with Custom

2024-01-15 16:56 UTC, tylergeorges commented on src/components/Overlays/Modal/Popout/index.tsx
> +  const windowIsMobile = useMediaQuery('screen and (max-width: 450px)');
created a Linear task for it here https://linear.app/widgetbot/issue/FR-191/create-predefined-media-query-strings-for-usemediaquery

2024-01-17 23:56 UTC, mason-rogers approved these changes

2024-01-18 16:43 UTC, merged