[FR-180] NextJS Fix Channel Highlighter Position
widgetbot-io/embed pull request #364
Opened 2023-12-04 16:16 UTC by tylergeorges

2023-12-13 15:12 UTC, mason-rogers approved these changes

2023-12-19 10:06 UTC, advaith1 requested changes
pretty good, but glitches when collapsing categories:

https://github.com/widgetbot-io/embed/assets/11778454/7a095d95-350d-45dc-9558-a91d2425f5a9

2024-01-04 23:07 UTC, advaith1 requested changes
still a bit misaligned for collapsed categories

https://github.com/widgetbot-io/embed/assets/11778454/fdca126d-eb77-4a2d-ab89-7299ec30e1f3

2024-01-04 23:07 UTC, advaith1 commented on src/components/Sidebar/ChannelsSidebar/Category/ChannelsContainer/Channel.tsx
> +        //   // console.log(target.offsetTop);
commented out code

2024-01-04 23:07 UTC, advaith1 commented on src/components/Sidebar/ChannelsSidebar/Category/index.tsx
> +      // if (channelsConRef.current && !channelsConHeight) {
commented out code

2024-01-09 01:46 UTC, advaith1 approved these changes

2024-01-09 17:27 UTC, merged