[FR-187] Implement graphql to api sticker data conversion
widgetbot-io/embed pull request #376
Opened 2024-01-11 09:19 UTC by JohnyTheCarrot

2024-01-13 15:00 UTC, Yomanz approved these changes
LGTM, but Advaith might have some concerns.

2024-01-15 11:45 UTC, advaith1 commented on src/util/convertToDiscord/convertField.ts
> +
can we implement this with an object instead? are there benefits to using the switch?

2024-01-15 12:06 UTC, advaith1 approved these changes

2024-01-15 12:09 UTC, advaith1 requested changes

2024-01-15 12:09 UTC, advaith1 commented on src/util/convertToDiscord/convertField.ts
> +    })),
this should return [APIStickerItem](https://discord.com/developers/docs/resources/sticker#sticker-item-object)[] - looks like that's already what [renderer](https://github.com/widgetbot-io/message-renderer/blob/master/src/Content/Sticker/index.tsx) wants
just change the type and remove the unused fields

2024-01-15 14:17 UTC, JohnyTheCarrot commented
squash and merge to avoid the second commit

2024-01-23 02:47 UTC, advaith1 approved these changes

2024-02-14 14:05 UTC, merged