[FR-189] NextJS Panel Resize Delay Fix
widgetbot-io/embed pull request #377
Opened 2024-01-11 15:53 UTC by tylergeorges

This PR fixes the resizing delay for TextChannelContainer when resizing a Panel

2024-01-12 10:07 UTC, advaith1 requested changes

2024-01-12 10:07 UTC, advaith1 commented on src/components/Sidebar/ResizablePanel/ResizablePanelHandle/index.tsx
> +      panelSibling.current.removeAttribute('transition');
this doesn't look right; wouldn't it remove a HTML `transition` attribute? shouldn't this change the style instead?

what effect is this block actually having?

2024-01-12 15:03 UTC, tylergeorges commented on src/components/Sidebar/ResizablePanel/ResizablePanelHandle/index.tsx
> +      panelSibling.current.removeAttribute('transition');
I add a HTML style attribute that sets transition to "none" when resizing/dragging the panel to override all transitions the sibling component may have.  This just removes the override when the user stops resizing

2024-01-15 10:25 UTC, mason-rogers commented on src/components/Sidebar/ResizablePanel/ResizablePanelHandle/index.tsx
> +      panelSibling.current.removeAttribute('transition');
@tylergeorges this is what html has data-* attributes for, you're not really supposed to add custom attributes

2024-01-15 18:04 UTC, tylergeorges commented on src/components/Sidebar/ResizablePanel/ResizablePanelHandle/index.tsx
> +      panelSibling.current.removeAttribute('transition');
@mason-rogers i wasnt adding a custom attribute, the only attribute being added was the "style" attribute but i just changed the sibling(TextChannelContainer) element to have a data attribute called data-resize-active which removes all transitions if set to true

2024-01-15 19:05 UTC, advaith1 commented on src/components/Sidebar/ResizablePanel/ResizablePanelHandle/index.tsx
> +    }
instead of setAttribute, should use dataset.resizeActive

2024-01-17 23:56 UTC, mason-rogers commented on src/components/Sidebar/ResizablePanel/ResizablePanelHandle/index.tsx
> +        sibling.removeAttribute('style');
do we need this? what styling is set on it?

2024-02-14 13:05 UTC, advaith1 reviewed
compared to the current nextjs branch, while this PR fixes the main channel container resizing, it makes the panel animation noticeably laggy and slower. is that a result of the changes in this PR, and can it be fixed?

2024-02-22 01:43 UTC, advaith1 approved these changes

2024-02-22 15:32 UTC, merged