[FR-198] NextJS Threads Popout Height Fix
widgetbot-io/embed pull request #385
Opened 2024-01-22 21:50 UTC by tylergeorges

2024-01-28 18:37 UTC, Yomanz approved these changes

2024-01-29 04:06 UTC, advaith1 requested changes
looks good, but can the loading indicator be vertically centered?
![image](https://github.com/widgetbot-io/embed/assets/11778454/3cca2bc9-b8b0-40c5-9355-05a1738b6ee7)

2024-02-09 15:44 UTC, tylergeorges commented
> looks good, but can the loading indicator be vertically centered? ![image](https://private-user-images.githubusercontent.com/11778454/300331104-3cca2bc9-b8b0-40c5-9355-05a1738b6ee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTM3NDYsIm5iZiI6MTcwNzQ5MzQ0NiwicGF0aCI6Ii8xMTc3ODQ1NC8zMDAzMzExMDQtM2NjYTJiYzktYjhiMC00MGM1LTkzNTUtMDVhMTczOGI2ZWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE1NDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ODdmMTE1M2FiN2Y1NzllZDNjMzdhNmIwYjg5Nzg2YmVjZGY5N2QwZTlmZTNhMGQ0OTliYmQ3MGU2ZjUwZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HooHe-TIVY247csgppLO0McbM9bH1VKm4D64cTbkdQk)

fixed

2024-02-14 10:19 UTC, advaith1 approved these changes

2024-02-14 14:20 UTC, merged