[FR-197] NextJS Popout Button Not Toggling Popout Fix
widgetbot-io/embed pull request #386
Opened 2024-01-22 22:39 UTC by tylergeorges

2024-01-29 04:03 UTC, advaith1 requested changes
this PR seems to break clicking outside a popout to close it

2024-02-08 13:45 UTC, mason-rogers commented
@tylergeorges see above ^

2024-02-09 00:28 UTC, tylergeorges commented
> this PR seems to break clicking outside a popout to close it

fixed

2024-02-12 18:27 UTC, mason-rogers approved these changes

2024-02-14 10:24 UTC, advaith1 approved these changes

2024-02-14 14:20 UTC, merged