[FR-194] NextJS Optimistic Message Rendering State
widgetbot-io/embed pull request #399
Opened 2024-02-13 21:51 UTC by tylergeorges

Adds support for rendering sent messages in their respective state, e.g. optimistic messages are grayed out and failed messages are red

For testing failed messages turn on network throttling in browser dev tools and set throttling to offline then send a message

2024-02-14 14:12 UTC, Yomanz commented on src/types/messages.types.ts
> +export enum SentMessageState {
what's this?

2024-02-14 14:13 UTC, Yomanz requested changes

2024-02-14 14:13 UTC, Yomanz commented on src/util/convertToDiscord/convertMessageToDiscord.ts
> +  optimistic: message.flags === SentMessageState.Sending,
What if discord decide to use these flags, wouldn't that cause issue?

2024-02-18 16:57 UTC, Yomanz approved these changes

2024-02-22 03:07 UTC, advaith1 approved these changes
looks good - on failed messages we should hide some of the actions and add a retry action, but that can be on a later PR

2024-02-22 17:33 UTC, merged